name: lint-and-coverage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies, static and migrations
        run: |
          make build && make install-all

      - name: start linter
        run: |
          uv run ruff check

      - name: code coverage and publish
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_REPORTER_ID}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
        with: 
          coverageCommand: make test-coverage
          debug: True