name: lint-and-coverage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Install dependencies, static and migrations
        run: |
          make build

      - name: start linter
        run: |
          uv run ruff check

      - uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          files: reports/lcov.info
